language: python
python:
- '3.5'
sudo: enabled
addons:
  ssh_known_hosts:
  - production-backend.etheroscope.info
  - staging-backend.etheroscope.info
  - test-backend.etheroscope.info
install:
- ./travis-install.sh
script:
- ./travis-test.sh
before_deploy:
- ./travis-before-deploy.sh
- openssl aes-256-cbc -K $encrypted_a606928c050a_key -iv $encrypted_a606928c050a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- echo "Adding SSH private key"
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- sudo ssh-add /tmp/deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: ls
  on:
    all_branches: true
notifications:
  email: false
