version: '2'
services:
  db:
    image: postgres:9.6.2
    ports:
      - "6969:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes_from:
      - dbdata

  # for persistance of database data
  dbdata:
    image: postgres:9.6.2
    volumes:
      - /var/lib/postgres
    command: "true"

  web:
    image: etheroscope
    command: mix do deps.get, ecto.create, ecto.migrate, phx.server
    links:
      - "db:db"
    environment:
      - MIX_ENV
      - ETHERSCAN_API_KEY
    volumes:
      - .:/app
    ports:
      - "4000:4000"
