version: '2'
services:
  db:
    image: postgres:9.6.2
    ports:
      - "6969:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes_from:
      - dbdata

  # for persistance of database data
  dbdata:
    image: postgres:9.6.2
    volumes:
      - /var/lib/postgres
    command: "true"

  web:
    image: etheroscope
    command: mix do deps.get, ecto.create, ecto.migrate, phx.server
    environment:
      - MIX_ENV=prod
      - ETHERSCAN_API_KEY
      - PORT=80
    volumes:
      - .:/app
    links:
      - "db:db"
    ports:
      - "6969:80"
